[project]
name = "crapette-python"
version = "0.1.0"
description = "Jeu de crapette en python / SDL"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "asttokens>=3.0.0",
    "colorama>=0.4.6",
    "executing>=2.2.0",
    "icecream>=2.1.4",
    "iniconfig>=2.1.0",
    "packaging>=25.0",
    "pluggy>=1.5.0",
    "pygments>=2.19.1",
    "pytest>=8.3.5",
    "ruff>=0.11.7",
]
